export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  SAVEPOSTS: 'SAVEPOSTS',
  DELETEPOSTS: 'DELETEPOSTS',
  //   NO_INTERNET: 'NO_INTERNET',
  // GETPRODUCT:"GETPRODUCT"
};
